### PR TITLE
Replaced bluebird with native promise support for PR #154

### PR DESCRIPTION
**Pull request by jasonrhodes**
If you are interested in what I was talking about re: removing the bluebird dependency and going with native promises (and node v0.12.15+ support for this version of the wrapper), here's a PR against your PR with the changes. :)

### CODE REVIEW

**Comment by jasonrhodes** [comment]
Ran some benchmark tests, looks like in node.js 4+ there's no difference so I vote for preferring native if performance was the main reason to use bluebird.

See benchmark notes: https://github.com/jasonrhodes/promisebench

**Comment by jasonrhodes** [comment]
Also I know that the benchmark I ran is far from complete, so I left the code there if anyone has suggestions of another test to run. The way I feel is that unless it's a very very obvious performance drop we don't need to optimize yet, and the tradeoff of having 1 less library dependency is worth it. :)

**Comment by awinder** [comment]
The bluebird benchmark suite is pretty thorough (from https://github.com/petkaantonov/bluebird), you can clone and run tests like:

```
git clone git@github.com:petkaantonov/bluebird.git
cd bluebird
npm install
./bench parallel
./bench doxbee (for more sequential workflows)
```

The perf differences were pretty stark locally (like 5x memory and 3x time for ES6 promises vs bluebird), but not trying to blow this idea up just figured since I checked it out I'd post the findings

**Comment by jasonrhodes** [comment]
Here are the results @awinder is talking about:

```
results for 10000 parallel executions, 1 ms per I/O op

file                                      time(ms)  memory(MB)
callbacks-baseline.js                          453       66.01
promises-bluebird.js                           674       97.64
callbacks-suguru03-neo-async-parallel.js       880       98.12
promises-bluebird-generator.js                1002      103.08
promises-cujojs-when.js                       1359      138.47
callbacks-caolan-async-parallel.js            1439      165.13
promises-then-promise.js                      2010      289.73
promises-calvinmetcalf-lie.js                 2054      372.78
promises-tildeio-rsvp.js                      2137      386.91
promises-lvivski-davy.js                      2786      251.88
promises-ecmascript6-native.js                3655      496.52
promises-dfilatov-vow.js                      3857      501.07
promises-medikoo-deferred.js                  6708      524.81
promises-obvious-kew.js                       8639      706.50
streamline-callbacks.js                        OOM         OOM
streamline-generators.js                       OOM         OOM

Platform info:
Darwin 15.2.0 x64
Node.JS 4.4.4
V8 4.5.103.35
Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz × 4
```

I don't really know what kind of stuff this suite is testing and how that compares to what we'll be using, but I'm perfectly fine if you want to just back this merge out and stick with bluebird for now and keep an eye on performance in V8 to see how it improves over time. I don't have time to investigate any further so if it's up in the air, I'm fine with being safe on the performance side of things, up to you @aydrian

**Comment by aydrian** [comment]
I've already merged everything in. Let's just go with what we have for now. We can put bluebird back in if need be later.

**Comment by jasonrhodes** [comment]
:+1:

**Pull request merged**
